### ISSUE TITLE
Add support for XML 

### ISSUE THREAD

**Issue by adityam** [adityam/filter#14]
From [mailing list](http://www.ntg.nl/pipermail/ntg-context/2014/077510.html)

> Is it possible to use 

```
 <paragraph> \startmarkdown bla... \stopmarkdown </paragraph>
```

> With my code (xmlflush) the start/stopmarkdown is printed without interpretation.

**Comment by ousia** [comment]
`\xmlcontext` and `\xmlflushcontext` solve the issue posted in the mailing list.

So, I guess the issue may be closed.

**Comment by adityam** [comment]
For future reference, could you link to the thread on the mailing list.
