### ISSUE TITLE
I can't read xml files

### ISSUE THREAD

**Issue by somenxavier** [adityam/filter#22]
With this filter:
```
\usemodule[filter]

\defineexternalfilter
    [python]
    [filtercommand={python3 \externalfilterinputfile\space > \externalfilteroutputfile}, location=text]
```

and this code:
```
import os.path

with open('./b.txt', 'r') as f:
	r = f.read()
	print(len(r))
```

all is fine except when b.txt is an XML file. I get this
```
references      > start problematic references

references      > unknown >    1: [][]

references      > stop problematic references
```

What happens?

**Comment by adityam** [comment]
Can you post a complete minimal working example with the XML file?

**Comment by somenxavier** [comment]
This is the contents of the `b.xml`. With other contents, I can't get any error:
```
<?xml version="1.0" standalone='yes'?>
<activitats>
  <activitat id="fitxes" tema="funcions" continguts="funció afí, dependència lineal, funcions a trossos">
    <presentacio tipus="tradicional" sintaxi="context" verbs="calcular">La fitxa blava i la fitxa vermella es mouen de la manera següent: la blava recorre les caselles d'una en una, mentre que la vermella les recorre de dues en dues però, després de cada moviment, s'espera un torn (figura~\in[]). Quina de les dues fitxes arribarà primer a la meta?
    </presentacio>
    <presentacio tipus="3-act" sintaxi="html" verbs="modelitzar">
     <actes>
       <u>vídeo fitxes</u>
       <dos></dos>
       <tres></tres>
     </actes>
    </presentacio>
  </activitat>
</activitats>
```

**Comment by adityam** [comment]
I don't have python3, but with python 2.7.8, the following works fine:
~~~
\usemodule[filter]

\traceexternalfilters

\defineexternalfilter
    [python]
    [filtercommand={python \externalfilterinputfile\space > \externalfilteroutputfile}, location=text,
    cache=no]

\startbuffer[data]
<?xml version="1.0" standalone='yes'?>
<activitats>
  <activitat id="fitxes" tema="funcions" continguts="funció afí, dependència lineal, funcions a trossos">
    <presentacio tipus="tradicional" sintaxi="context" verbs="calcular">La fitxa blava i la fitxa vermella es mouen de la manera següent: la blava recorre les caselles d'una en una, mentre que la vermella les recorre de dues en dues però, després de cada moviment, s'espera un torn (figura~\in[]). Quina de les dues fitxes arribarà primer a la meta?
    </presentacio>
    <presentacio tipus="3-act" sintaxi="html" verbs="modelitzar">
     <actes>
       <u>vídeo fitxes</u>
       <dos></dos>
       <tres></tres>
     </actes>
    </presentacio>
  </activitat>
</activitats>
\stopbuffer

\savebuffer[list=data, file=b.xml, prefix=no]

\starttext
\startpython
import os.path

with open('./b.xml', 'r') as f:
    r = f.read()
    print(len(r))
\stoppython

\stoptext
~~~

**Comment by somenxavier** [comment]
Here not, with python2 and python3. I don't know why!

**Comment by adityam** [comment]
Can you post the complete log file that you get when running my example?

**Comment by somenxavier** [comment]
I push my contents [here](https://github.com/somenxavier/bug).

**Comment by adityam** [comment]
In the first example (in your original bug report) you use `print(len(r))` but in the second example (the one in your repo) you use `print(r)`. So, the entire contents of your `xml` file are input _as if you had literally typed them in your `tex` file_. This means that you are compiling a `tex` file:

~~~
\starttext
..... \in[] ....
\stoptext
~~~

The error message:

~~~
references      > start problematic references

references      > unknown >    1: [][]

references      > stop problematic references
~~~

is telling you that `<empty string>` reference was not found.

**Comment by somenxavier** [comment]
With this
```
\startpython
from bs4 import BeautifulSoup
import json, os.path

with open('./dades/activitats.xml', 'r') as f:
	r = f.read()
	print(len(r))

#	soup = BeautifulSoup(r, "xml")
#
#	for a in soup.find_all("activitat", {'id': 'fitxes'}):
#		for p in a.find_all("presentacio"):
#			print(p.text)

\stoppython
```
I obtained the same result (empty string). What can I do=?

**Comment by adityam** [comment]
1. Remove the `.tuc` file and try again.

2. If that does not work, remove the `.tuc` file and add 
`\traceexternalfilters`. This will not remove the `\jobname-temp-*.tmp` 
file. Open this file in an editor to see that it is written correctly. Run 
it through python to ensure that you are getting correct output.

**Comment by somenxavier** [comment]
> add `\traceexternalfilters`
where?

**Comment by adityam** [comment]
See the example that I had posted.

**Comment by somenxavier** [comment]
I do not understand nothing.

**Comment by somenxavier** [comment]
Let's do simply example:

\startpython
import yaml

print("\startitemize")

with open('dades/accions.yaml', 'r') as f:
	r = yaml.load(f)
	print(r)
	for a in r:
		print("\item {0}".format(a))

print("\stopitemize")

\stoppython


This gives me blank string. How can I modify it for proper printing?

Thanks,

**Comment by adityam** [comment]
Does this run correctly if you save the contents as a python file and compile it?

**Comment by somenxavier** [comment]
Yes

**Comment by adityam** [comment]
I don't know why this is not working. Can you create a **complete** and **minimal** example that does not work (similar to the one that I created in [my comment above](https://github.com/adityam/filter/issues/22#issuecomment-127661600)

**Comment by somenxavier** [comment]
I don't know too. With json it [works](https://github.com/somenxavier/bug/commit/48bd2c9055e784670b0239783615021c05df7d59)

**Comment by somenxavier** [comment]
Ruby does not do that. Perfect with ruby.
