### ISSUE TITLE
highlighting code in XML sources

### ISSUE THREAD

**Issue by ousia** [adityam/filter#24]
@adityam,

to be able to use your module with XML sources for code highlighting, we would need to have two commands:

* `\vimtypebuffer`
* `\vimtypeinlinebuffer

They should have two options, the name of the buffer to be typeset and the syntax highlight to apply.

ConTeXt itself has two similar commands: `\typebuffer` and `\typeinlinebuffer`. And the `m-scite` has the commands `\scitebuffer` and `\sciteinlinebuffer`.

Could you consider adding both commands to the `vim` module?

BTW, it would be great when there is no need to use `\definevimtyping` if the user selects the right syntax highlight to be applied.

**Comment by adityam** [comment]
Sorry, I somehow missed you question. This feature is already available.

```
\usemodule[vim]
\definevimtyping[C][syntax=C]

\startbuffer[test]
#include <stdio.h>
main ()
{
  printf("Hello world\n");
}
\stopbuffer

\startbuffer[test2]
int a; a = 10;
\stopbuffer

\starttext
\processCbuffer[test]

\processCbuffer[location=text][test2]
\stoptext
```

Also, you don't need to define a new vimtyping for each syntax:
```
\usemodule[vim]
\definevimtyping[vimtyping][syntax=C]

\starttext
\startvimtyping[syntax=ruby]
  def test
      puts("Hello world\n")
  end
\stopvimtyping

\stoptext
```
