### ISSUE TITLE
reusing cached filter output

### ISSUE THREAD

**Issue by expilo** [adityam/filter#27]
I would like to reuse cached output between context runs but the following still makes all the calls to pandoc every time I execute context. Is it possible to run context without calling external program defined in \defineexternalfilter and still use the  external filter output from previous runs?
```

\defineexternalfilter
  [pandoc]
  [
    filter={pandoc --no-wrap -f \externalfilterparameter{format} -t context 
                   -o \externalfilteroutputfile},
    format=twiki,
    directory=output,
    spacebefore=none,
    spaceafter=none,
    indentnext=yes,
    cache=yes
  ]

I am using ConTeXt standalone distribution and bundled modules, context  version is 2018.09.01 23:10
```

**Comment by adityam** [comment]
Use `state=stop`.

**Comment by expilo** [comment]
Many thanks! That's a huge gain.

**Comment by expilo** [comment]
Thanks. In my case, with lots of pandoc environments, went down from 30s to 22s. Worth trying definitely.
