### ISSUE TITLE
Question: Does filter module work with ConTeXtLMTX and can it be used in Windows?

### ISSUE THREAD

**Issue by Delanii** [adityam/filter#40]
Hello Mr. Aditya,
I would like to ask whether the "filter" module does work with (? newest) ConTeXtLMTX and if it does, how one can install it on Windows OS? There is already a guide on context garden [here](https://wiki.contextgarden.net/Modules#ConTeXt_LMTX), but it assumes Linux OS (I guess, I dont have `rsync` command avaible on Windows10).
Currently, I am learning ConTeXt with `Standalone` version from 2019, sometimes switching to TeXlive. So far, I have been using LaTeX with PythonTeX, but recently I am in need to also use xml data, for which ConTeXt would be better suited, but I also need functionalities similar to PythonTeX, for which your modules fits quite nicely.
Thank you in advance for any help,
regards Tomas

**Comment by adityam** [comment]
The filter module does work with LMTX and also works with Windows. 

1. If you are using context standalone, then you can install the module using `first-setup.bat` from context standalone. Use

        first-setup.bat --modules="t-filter"

2. If you just want to install `t-filter` modules without using `rsync`, simply download the latest version of the module from [module.contextgarden.net](https://modules.contextgarden.net/cgi-bin/module.cgi/ruid=1153128881/action=view/id=52) (there is a small [download](https://modules.contextgarden.net/dl/t-filter-2020.06.29.zip) link at the bottom). Put the downloaded zip file in `$TEXMFHOME` (which should be `C:\Users\<Your-Username>\texmf` and unzip it there (make sure that it is unzipped at the top level of that folder and not in a sub-directory. Then you should be able to use the filter module.

**Comment by Delanii** [comment]
Thank you very much for your help Mr. Aditya, after few attempts it works. Eventhough it is straightforward, for some reason I was getting errors about ConTeXt being unable to make format files, but another try today was successfull (also for other modules).
Regards, Tomas
