### ISSUE TITLE
Test 51-colorscheme.tex is failing - both comments in blue color

### ISSUE THREAD

**Issue by manymachines** [adityam/filter#42]
This is related to issue #37.  I had confirmed this was working after the issue was closed last year.  I revisited this again today with the latest  ConTeXt LMTX (I don't know if the root cause is new ConTeXt version or not).

I downloaded  modules from https://modules.contextgarden.net and installed manually.
t-filter-2020.06.29.zip
t-vim-2020.09.15.zip

$ grep ver: 51-colorscheme.log

system          > ConTeXt  ver: 2021.02.05 17:45 LMTX  fmt: 2021.2.5  int: english/english
loading         > Vim syntax highlighting (ver: 2020.06.29)
loading         > Filter (ver: 2020.06.29)
loading         > Module Catcodes (ver: 2018.04.16)
loading         > Code syntax highlighting (ver: 2020.06.29)
loading         > Syntax highlighting groups (ver: 2020.06.29)

I tested with both 
$ context  51-colorscheme.tex
system          > ConTeXt  ver: 2021.02.05 17:45 LMTX  fmt: 2021.2.5  int: english/english
$ context --luatex 51-colorscheme.tex
system          > ConTeXt  ver: 2021.02.05 17:45 MKIV  fmt: 2021.2.7  int: english/english

The result was the same in that the comment lines are both displayed as blue in the PDF.

**Comment by adityam** [comment]
I can confirm this bug. I'll check why this is happening.

**Comment by adityam** [comment]
OK. Somehow the fix in the old patch was "lost". I am not sure what exactly happened, but at some stage I merged an old file back into the tree and the change was lost. Reapplying it. Can you test the [syntaxcolor](https://github.com/adityam/filter/tree/syntaxcolor) branch and see if that fixes the issue at your end. If so, I will merge that commit.

**Comment by manymachines** [comment]
I verified the fix on master branch.  Thanks!
