### ISSUE TITLE
css path is inserted wrongly

### ISSUE THREAD

**Issue by hernot** [adityam/filter#43]
Hi
It too me a long time to finally test what we have achieved last year til june on my lecturenotes.
What i have figured now is that when adding the css using
```
\setupexport[ ... , ... ,cssfile=\vimtypingcssfile]
```
Than the following line is included on my linux system using below mentioned standalone installation of context.

```
<!-- *-div.html -->
<link type="text/css" rel="stylesheet" href="styles/<prefixpath>/tex/texmf-modules/tex/context/third/vim/vimtyping-default.css" />

<!-- *-div.xhtml -->
<!-- not included and thus missing-->

<!-- *-raw.xml -->
<?xml-stylesheet type="text/css" href="styles/<prefixpath>/tex/texmf-modules/tex/context/third/vim/vimtyping-default.css" ?>

<!-- *-tag.xml -->
<?xml-stylesheet type="text/css" href="styles/<prefixpath>/tex/texmf-modules/tex/context/third/vim/vimtyping-default.css" ?>
```

I can't tell whether this is the fault of t-filter or t-vim module or a bug in context. The default workarround is to once include using `\vimtypingscriptfile` to get it copied and than for the next runs replace by `cssfile=vimtyping-default.css`.

```
mtx-context     | ConTeXt Process Management 1.04
mtx-context     |
mtx-context     | main context file: <prefixpath>/tex/texmf-context/tex/context/base/mkiv/context.mkiv
mtx-context     | current version: 2021.02.14 16:39
mtx-context     | main context file: <prefixpath>/tex/texmf-context/tex/context/base/mkxl/context.mkxl
mtx-context     | current version: 2021.02.14 16:39
```
`<prefixpath>` ... the base directory path standalone context installation was installed to

--------------------------
ps.: I think i also have found why line numbering and vim-typing does not play well in float environments. I still have to check home with latest context installation and github t-vim sources. keep you posted

**Comment by adityam** [comment]
Just so that I understand correctly, the desired behavior is to copy the file to the `export/css` directory?

**Comment by hernot** [comment]
Yes. It is assumed by exporter that it is copied there. I didn't know that either and thus it prefixes the path absolute path by `styles/`. I think that is cause the output of exporter could be directly be the root directory of a full web page like the context-garden. In this case it is likely that no files outside document root are allowed to be accessed.

**Comment by adityam** [comment]
This is an upstream bug. I have reported it to the context mailing list and it should be fixed soon.

**Comment by adityam** [comment]
This has been fixed upstream (relevant commit: [0d3005](https://github.com/contextgarden/context-mirror/commit/0d300509bdd7497fd376844b2326f5917636590e)).

**Comment by hernot** [comment]
Ok thanks wait till next standalone release can be grabed via install.sh
