### ISSUE TITLE
Accents are not displayed when using filter with R

### ISSUE THREAD

**Issue by fthalabi** [adityam/filter#44]
Minimal example to reproduce the issue:

```

\usemodule[filter]

\startbuffer[r::before]
library(tidyverse)
\stopbuffer

\defineexternalfilter
  [R]
  [filtercommand={R CMD BATCH  \externalfilterinputfile\space \externalfilteroutputfile},
   output=\externalfilterbasefile.out,
   bufferbefore={r::before},
   continue=no,
   read=no]


\starttext

\startR
dt <- tibble(x = 1:5, y = x)
plot <- ggplot(data = dt, mapping = aes(x = x, y = y, color = factor(x))) + geom_point() + labs(title = "áéíóú")
ggsave('plot.pdf',plot = plot, device = cairo_pdf,width = 5,height=5,unit='cm')
\stopR

\externalfigure[plot.pdf]
\stoptext

```

The context output: 
![image](https://user-images.githubusercontent.com/54052666/112708476-f2826a00-8e90-11eb-89b0-c63d602f44bf.png)

The same  R code run with Rscript gives:

![image](https://user-images.githubusercontent.com/54052666/112708420-b6e7a000-8e90-11eb-8eb7-b92ea6117886.png)

I would be very grateful for any help in this issue, because i don't wanna waste anyone time i tried to solve it myself, but i couldn't. 

Thanks in advance, 
Fernando H.

**Comment by adityam** [comment]
Most likely because the `locale` seen by context is different from your system `locale`. Try adding

```
Sys.setlocale(category="LC_ALL", locale="en_US.UTF-8")
```
in `r::before`.

**Comment by fthalabi** [comment]
You are right, it works. Thanks.

**Comment by fthalabi** [comment]
You are right, it works. Thanks.
