### ISSUE TITLE
numberdistance not considering margin

### ISSUE THREAD

**Issue by champignoom** [adityam/filter#53]
```tex
\usemodule[vim]

\setupvimtyping[vimcommand=nvim]
\definevimtyping[CPP][syntax=cpp, numbering=yes, numberdistance=1em, margin=10em]

\starttext
\startCPP
#include <iostream>
using std::cout;

int main() {
    cout <<"Hello world!\n";
}
\stopCPP
\stoptext
```

![t-vim-margin-numbering](https://user-images.githubusercontent.com/66909116/132237478-e37f5806-447f-47e6-b49f-8c3adef33398.png)

Line numbers are way farther than 1em to the code.

**Comment by champignoom** [comment]
`numbering=-9em` works in this case, so it's probably sufficient to clarify the vim-README a bit:

> To change the distance between the numbers and the <s>rest of the code</s> text area, use numberdistance=... option.

**Comment by adityam** [comment]
Thanks. Updated the documentation with a bit more detail.

**Comment by champignoom** [comment]
> By default, the numbers are placed on the right of the text area.

Isn't it on the left by default?

**Comment by adityam** [comment]
D'oh. Fixed.
