### ISSUE TITLE
numbering in conflict with itemize[columns]

### ISSUE THREAD

**Issue by champignoom** [adityam/filter#54]
```tex
\usemodule[vim]
\setupvimtyping[vimcommand=nvim]
\definevimtyping[code][numbering=yes]

\starttext
\startcode
foobar
foobar
foobar
\stopcode

\startitemize[columns] \stopitemize
\startitemize[columns] \stopitemize
\startitemize[columns] \stopitemize

\stoptext
```

![t-vim-columns](https://user-images.githubusercontent.com/66909116/132332583-6adf19b9-9c68-4c80-bf04-6244d54c97f7.png)

**Comment by adityam** [comment]
This is an upstream bug:

    \starttext
    \startlinenumbering
      \input tufte
    \stoplinenumbering

    \startitemize[columns] \item one \stopitemize
    \startitemize[columns] \item one \stopitemize
    \startitemize[columns] \item one \stopitemize

    \stoptext

Please report on the context mailing list.
